# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 178fe5b065bbc504a75953c21c5d56af631948e11ec4e84dd1e21de99663efcbafcfcd024108ccc30c548d73044597c68be35c05d7f131b15096b5fb311b8972

test:
  secret_key_base: 606ac27c623211861f0611bcb99918bd82bf3b7baadf43a96d04f14246ef435bb359449cbc46c0acfe8cb0b5cbee01768c03b2921b232265e316873147f2fffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
